routes/admin.php
<?php

use App\Http\Controllers\Admin\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Admin\ShowProducts;
use App\Http\Livewire\Admin\CreateProduct;
use App\Http\Livewire\Admin\EditProduct;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Livewire\Admin\BrandComponent;
use App\Http\Livewire\Admin\CityComponent;
use App\Http\Livewire\Admin\ShowCategory;
use App\Http\Livewire\Admin\ShowState;
use App\Http\Livewire\Admin\StateComponent;
use App\Http\Livewire\Admin\UserComponent;

Route::get('/', ShowProducts::class)->name('admin.index');

Route::get('products/create', CreateProduct::class)->name('admin.products.create');

Route::get('products/{product}/edit', EditProduct::class)->name('admin.products.edit');

Route::post('products/{product}/files', [ProductController::class, 'files'])->name('admin.products.files');

Route::get('categories', [CategoryController::class, 'index'])->name('admin.categories.index');

Route::get('cateogries/{category}', ShowCategory::class)->name('admin.categories.show');

Route::get('brands', BrandComponent::class)->name('admin.brands.index');

Route::get('orders', [OrderController::class, 'index'])->name('admin.orders.index');

Route::get('orders/{order}', [OrderController::class, 'show'])->name('admin.orders.show');

Route::get('states', StateComponent::class)->name('admin.states.index');

Route::get('states/{state}', ShowState::class)->name('admin.states.show');

Route::get('cities/{city}', CityComponent::class)->name('admin.cities.index');

Route::get('users', UserComponent::class)->name('admin.users.index');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WellcomeController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\WebhooksController;
use App\Http\Livewire\CreateOrder;
use App\Http\Livewire\PaymentOrder;
use App\Http\Livewire\ShoppingCart;

Route::get('/', WellcomeController::class);

Route::get('search', SearchController::class)->name('search');

Route::get('categories/{category}', [CategoryController::class, 'show'])->name('categories.show');

Route::get('product/{product}', [ProductController::class, 'show'])->name('products.show');

Route::get('shopping-cart', ShoppingCart::class)->name('shopping-cart');

Route::middleware(['auth', 'verified'])->group(function () {

    Route::get('orders', [OrderController::class, 'index'])->name('orders.index');

    Route::get('orders/create', CreateOrder::class)->name('orders.create');

    Route::get('orders/{order}', [OrderController::class, 'show'])->name('orders.show');

    Route::get('orders/{order}/payment', PaymentOrder::class)->name('orders.payment');

    Route::get('orders/{order}/pay', [OrderController::class, 'pay'])->name('orders.pay');

    Route::post('webhooks', WebhooksController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    const BORRADOR = 1;
    const PUBLICADO = 2;

    protected $guarded = ['id', 'create_at', 'update_at'];

    //Accesores
    public function getStockAttribute()
    {
        if ($this->subcategory->size) {
            return ColorSize::whereHas('size.product', function (Builder $query) {
                $query->where('id', $this->id);
            })->sum('quantity');
        } elseif ($this->subcategory->color) {
            return ColorProduct::whereHas('product', function (Builder $query) {
                $query->where('id', $this->id);
            })->sum('quantity');
        } else {
            return $this->quantity;
        }
    }
    //Relación uno a muchos
    public function sizes()
    {
        return $this->hasMany(Size::class);
    }

    //Relación uno a muchos inversa
    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function subcategory()
    {
        return $this->belongsTo(Subcategory::class);
    }
    //Relación muchos a muchos
    public function colors()
    {
        return $this->belongsToMany(Color::class)->withPivot('quantity', 'id');
    }
    //Relación uno a muchos polímorfica
    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }
    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Livewire/AddCartItem.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Support\Facades\Storage;

class AddCartItem extends Component
{
    public $product, $quantity;
    public $qty = 1;
    public $options = [
        'color_id' => null,
        'size_id' => null
    ];

    public function mount()
    {
        $this->quantity = qty_available($this->product->id);
        if ($this->product->images->count()) {
            $this->options['image'] = Storage::url($this->product->images->first()->url);
        }
    }
    public function decrement()
    {
        $this->qty = $this->qty - 1;
    }
    public function increment()
    {
        $this->qty = $this->qty + 1;
    }
    public function addItem()
    {
        Cart::add([
            'id' => $this->product->id,
            'name' => $this->product->name,
            'qty' => $this->qty,
            'price' => $this->product->price,
            'weight' => 550,
            'options' => $this->options,
        ]);

        $this->quantity = qty_available($this->product->id);
        $this->reset('qty');
        $this->emitTo('dropdown-cart', 'render');
    }
    public function render()
    {
        return view('livewire.add-cart-item');
    }
}

app/Http/Livewire/AddCartItemColor.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Support\Facades\Storage;

class AddCartItemColor extends Component
{
    public $product, $colors;
    public $color_id = "";
    public $qty = 1;
    public $quantity = 0;
    public $options = [
        'size_id' => null
    ];

    public function mount()
    {
        $this->colors = $this->product->colors;
        if ($this->product->images->count()) {
            $this->options['image'] = Storage::url($this->product->images->first()->url);
        }
    }
    public function updatedColorId($value)
    {
        $color = $this->product->colors->find($value);
        $this->quantity = qty_available($this->product->id, $color->id);
        $this->options['color'] = $color->name;
        $this->options['color_id'] = $color->id;
    }
    public function decrement()
    {
        $this->qty = $this->qty - 1;
    }
    public function increment()
    {
        $this->qty = $this->qty + 1;
    }
    public function addItem()
    {
        Cart::add([
            'id' => $this->product->id,
            'name' => $this->product->name,
            'qty' => $this->qty,
            'price' => $this->product->price,
            'weight' => 550,
            'options' => $this->options,
        ]);
        $this->quantity = qty_available($this->product->id, $this->color_id);
        $this->reset('qty');
        $this->emitTo('dropdown-cart', 'render');
    }
    public function render()
    {
        return view('livewire.add-cart-item-color');
    }
}

app/Http/Livewire/AddCartItemSize.php
<?php

namespace App\Http\Livewire;

use App\Models\Size;
use Livewire\Component;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Support\Facades\Storage;

class AddCartItemSize extends Component
{
    public $product, $sizes;
    public $color_id = "";
    public $qty = 1;
    public $quantity = 0;
    public $size_id = "";
    public $colors = [];
    public $options = [];

    public function mount()
    {
        $this->sizes = $this->product->sizes;
        if ($this->product->images->count()) {
            $this->options['image'] = Storage::url($this->product->images->first()->url);
        }
    }
    public function updatedSizeId($value)
    {
        $size = Size::find($value);
        $this->colors = $size->colors;
        $this->options['size'] = $size->name;
        $this->options['size_id'] = $size->id;
    }
    public function updatedColorId($value)
    {
        $size = Size::find($this->size_id);
        $color = $size->colors->find($value);
        $this->quantity = qty_available($this->product->id, $color->id, $size->id);
        $this->options['color'] = $color->name;
        $this->options['color_id'] = $color->id;
    }
    public function decrement()
    {
        $this->qty = $this->qty - 1;
    }
    public function increment()
    {
        $this->qty = $this->qty + 1;
    }
    public function addItem()
    {
        Cart::add([
            'id' => $this->product->id,
            'name' => $this->product->name,
            'qty' => $this->qty,
            'price' => $this->product->price,
            'weight' => 550,
            'options' => $this->options,
        ]);
        $this->quantity = qty_available($this->product->id, $this->color_id, $this->size_id);
        $this->reset('qty');
        $this->emitTo('dropdown-cart', 'render');
    }
    public function render()
    {
        return view('livewire.add-cart-item-size');
    }
}

app/Http/Livewire/AddFavoriteItem.php
<?php

namespace App\Http\Livewire;

use App\Models\FavoriteProduct;
use App\Models\Product;
use Livewire\Component;

class AddFavoriteItem extends Component
{
    
    public $product, $favorites, $favorite;
    /*
    public function mount()
    {
        $this->getFavorites();
    }
    public function getFavorites()
    {
        $this->favorites = FavoriteProduct::where('user_id', 1);
    }
    public function addFavorite()
    {
        FavoriteProduct::create([
            'product_id' => $this->product->id,
            'user_id' => 1,
        ]);
    }
    public function deletefavorite(FavoriteProduct $favorite)
    {
        $favorite->delete();
    }
    public function render()
    {
        return view('livewire.add-favorite-item');
    }*/
}

app/Http/Livewire/Admin/BrandComponent.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Brand;
use Livewire\Component;

class BrandComponent extends Component
{
    public $brands, $brand;
    protected $listeners = ['delete'];
    public $createForm = [
        'name' => null
    ];
    public $editForm = [
        'open' => false,
        'name' => null
    ];

    public $rules = [
        'createForm.name' => 'required'
    ];
    public $validationAttributes = [
        'createForm.name' => 'nombre',
        'editForm.name' => 'nombre'
    ];
    public function mount()
    {
        $this->getBrands();
    }
    public function getBrands()
    {
        $this->brands = Brand::all();
    }
    public function save()
    {
        $this->validate();
        Brand::create($this->createForm);
        $this->reset('createForm');
        $this->getBrands();
    }
    public function edit(Brand $brand)
    {
        $this->brand = $brand;
        $this->editForm['open'] = true;
        $this->editForm['name'] = $brand->name;
    }
    public function update()
    {
        $this->validate([
            'editForm.name' => 'required'
        ]);
        $this->brand->update($this->editForm);
        $this->reset('editForm');
        $this->getBrands();
    }
    public function delete(Brand $brand)
    {
        $brand->delete();
        $this->getBrands();
        $this->emit('deleted');
    }

    public function render()
    {
        return view('livewire.admin.brand-component')->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/CityComponent.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\City;
use App\Models\Colony;
use Livewire\Component;

class CityComponent extends Component
{
    protected $listeners = ['delete'];

    public $city, $colonies, $colony;

    public $createForm = [
        'name' => '',
    ];
    public $editForm = [
        'open' => false,
        'name' => ''
    ];
    public $validationAttributes = [
        'createForm.name' => 'nombre',
        'editForm.name' => 'nombre',
    ];

    public function mount(City $city)
    {
        $this->city = $city;
        $this->getColonies();
    }
    public function getColonies()
    {
        $this->colonies = Colony::where('city_id', $this->city->id)->orderBy('name', 'ASC')->get();
    }
    public function save()
    {
        $this->validate([
            'createForm.name' => 'required',
        ]);
        $this->city->colonies()->create($this->createForm);
        $this->reset('createForm');
        $this->getColonies();
        $this->emit('saved');
    }
    public function edit(Colony $colony)
    {
        $this->colony = $colony;
        $this->editForm['open'] = true;
        $this->editForm['name'] = $colony->name;
    }
    public function update()
    {
        $this->colony->name = $this->editForm['name'];
        $this->colony->save();
        $this->reset('editForm');
        $this->getColonies();
        $this->emit('updated');
    }
    public function delete(Colony $colony)
    {
        $colony->delete();
        $this->getColonies();
        $this->emit('deleted');
    }
    public function render()
    {
        return view('livewire.admin.city-component')->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/ColorProduct.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Color;
use Livewire\Component;
use App\Models\ColorProduct as Pivot;

class ColorProduct extends Component
{
    public $product, $colors, $color_id, $quantity, $open = false;

    public $pivot, $pivot_color_id, $pivot_quantity;

    protected $listeners = ['delete'];

    protected $rules = [
        'color_id' => 'required',
        'quantity' => 'required|numeric'
    ];
    public function mount()
    {
        $this->colors = Color::all();
    }
    public function save()
    {
        $this->validate();
        $pivot = Pivot::where('color_id', $this->color_id)
            ->where('product_id', $this->product->id)
            ->first();
        if ($pivot) {
            $pivot->quantity = $pivot->quantity + $this->quantity;
            $pivot->save();
        } else {
            $this->product->colors()->attach([
                $this->color_id => [
                    'quantity' => $this->quantity
                ]
            ]);
        }
        $this->reset(['color_id', 'quantity']);
        $this->emit('saved');
        $this->product = $this->product->fresh();
    }
    public function edit(Pivot $pivot)
    {
        $this->open = true;
        $this->pivot = $pivot;
        $this->pivot_color_id = $pivot->color_id;
        $this->pivot_quantity = $pivot->quantity;
    }
    public function update()
    {
        $this->pivot->color_id = $this->pivot_color_id;
        $this->pivot->quantity = $this->pivot_quantity;
        $this->pivot->save();
        $this->product = $this->product->fresh();
        $this->reset('open');
    }
    public function delete(Pivot $pivot)
    {
        $pivot->delete();
        $this->product = $this->product->fresh();
    }
    public function render()
    {
        $product_colors = $this->product->colors;
        return view('livewire.admin.color-product', compact('product_colors'));
    }
}

app/Http/Livewire/Admin/ColorSize.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Color;
use Livewire\Component;
use App\Models\ColorSize as Pivot;

class ColorSize extends Component
{
    public $size, $colors, $color_id, $quantity, $open = false;
    public $pivot, $pivot_color_id, $pivot_quantity;
    protected $listeners = ['delete'];
    protected $rules = [
        'color_id' => 'required',
        'quantity' => 'required|numeric'
    ];
    public function mount()
    {
        $this->colors = Color::all();
    }
    public function save()
    {
        $this->validate();

        $pivot = Pivot::where('color_id', $this->color_id)
            ->where('size_id', $this->size->id)
            ->first();
        if ($pivot) {
            $pivot->quantity = $pivot->quantity + $this->quantity;
            $pivot->save();
        } else {
            $this->size->colors()->attach([
                $this->color_id => [
                    'quantity' => $this->quantity
                ]
            ]);
        }
        $this->reset(['color_id', 'quantity']);
        $this->emit('saved');
        $this->size = $this->size->fresh();
    }
    public function edit(Pivot $pivot)
    {
        $this->open = true;
        $this->pivot = $pivot;
        $this->pivot_color_id = $pivot->color_id;
        $this->pivot_quantity = $pivot->quantity;
    }
    public function update()
    {
        $this->pivot->color_id = $this->pivot_color_id;
        $this->pivot->quantity = $this->pivot_quantity;
        $this->pivot->save();
        $this->size = $this->size->fresh();
        $this->reset('open');
    }
    public function delete(Pivot $pivot)
    {
        $pivot->delete();
        $this->size = $this->size->fresh();
    }
    public function render()
    {
        $size_colors = $this->size->colors;
        return view('livewire.admin.color-size', compact('size_colors'));
    }
}

app/Http/Livewire/CartMobil.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class CartMobil extends Component
{
    public function render()
    {
        return view('livewire.cart-mobil');
    }
}

resources/views/livewire/add-cart-item-color.blade.php
<div x-data>
    <p class="text-xl text-gray-700">Color:</p>
    <select wire:model="color_id" class="form-control w-full">
        <option value="" selected disabled>Seleccionar un color</option>
        @foreach ($colors as $color)
            <option class="capitalize" value="{{ $color->id }}">{{ __($color->name) }}</option>
        @endforeach
    </select>

    <p class="text-gray-700 my-4"><span class="font-semibold text-lg">Stock disponible:</span>
        @if ($quantity)
            {{ $quantity }}
        @else
            {{ $product->stock }}
        @endif
    </p>

    <div class="flex">
        <div class="mr-4">
            <x-jet-secondary-button disabled x-bind:disabled="$wire.qty <= 1" wire:loading.attr="disabled"
                wire:target="decrement" wire:click="decrement">
                -
            </x-jet-secondary-button>
            <span class="mx-2 text-gray-700">{{ $qty }}</span>
            <x-jet-secondary-button x-bind:disabled="$wire.qty >= $wire.quantity" wire:loading.attr="disabled"
                wire:target="increment" wire:click="increment">
                +
            </x-jet-secondary-button>
        </div>
        <div class="flex-1">
            <x-button x-bind:disabled="!$wire.quantity" color="Orange" class="w-full" wire:click="addItem"
                wire:loading.attr="disabled" wire:target="addItem">
                <i class="fas fa-spinner animate-spin text-white text-lg" wire:loading wire:target="addItem"></i>
                Agregar al carrito de compras
            </x-button>
        </div>
    </div>

</div>

resources/views/livewire/add-cart-item-size.blade.php
<div x-data>
    <div>
        <p class="text-xl text-gray-700">Talla:</p>
        <select wire:model="size_id" class="form-control w-full">
            <option value="" selected disabled>Seleccione una talla</option>
            @foreach ($sizes as $size)
                <option value="{{ $size->id }}">{{ $size->name }}</option>
            @endforeach
        </select>
    </div>
    <div class="mt-2">
        <p class="text-xl text-gray-700">Color:</p>
        <select wire:model="color_id" class="form-control w-full">
            <option value="" selected disabled>Seleccione un color</option>
            @foreach ($colors as $color)
                <option class="capitalize" value="{{ $color->id }}">{{ __($color->name) }}</option>
            @endforeach
        </select>

        <p class="text-gray-700 my-4"><span class="font-semibold text-lg">Stock disponible:</span>
            @if ($quantity)
                {{ $quantity }}
            @else
                {{ $product->stock }}
            @endif
        </p>

        <div class="flex">
            <div class="mr-4">
                <x-jet-secondary-button disabled x-bind:disabled="$wire.qty <= 1" wire:loading.attr="disabled"
                    wire:target="decrement" wire:click="decrement">
                    -
                </x-jet-secondary-button>
                <span class="mx-2 text-gray-700">{{ $qty }}</span>
                <x-jet-secondary-button x-bind:disabled="$wire.qty >= $wire.quantity" wire:loading.attr="disabled"
                    wire:target="increment" wire:click="increment">
                    +
                </x-jet-secondary-button>
            </div>
            <div class="flex-1">
                <x-button x-bind:disabled="!$wire.quantity" color="Orange" class="w-full" wire:click="addItem"
                    wire:loading.attr="disabled" wire:target="addItem">
                    <i class="fas fa-spinner animate-spin text-white text-lg" wire:loading wire:target="addItem"></i>
                    Agregar al carrito de compras
                </x-button>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/add-cart-item.blade.php
<div x-data>

    <p class="text-gray-700 mb-4"><span class="font-semibold text-lg">Stock disponible:</span> {{ $quantity }}</p>
    <div class="flex">
        <div class="mr-4">
            <x-jet-secondary-button disabled x-bind:disabled="$wire.qty <= 1" wire:loading.attr="disabled"
                wire:target="decrement" wire:click="decrement">
                -
            </x-jet-secondary-button>
            <span class="mx-2 text-gray-700">{{ $qty }}</span>
            <x-jet-secondary-button x-bind:disabled="$wire.qty >= $wire.quantity" wire:loading.attr="disabled"
                wire:target="increment" wire:click="increment">
                +
            </x-jet-secondary-button>
        </div>
        <div class="flex-1">
            <x-button class="w-full" x-bind:disabled="$wire.qty > $wire.quantity" color="Orange" wire:click="addItem"
                wire:loading.attr="disabled" wire:target="addItem">
                <i class="fas fa-spinner animate-spin text-white text-lg" wire:loading wire:target="addItem"></i>
                Agregar al carrito de compras
            </x-button>
        </div>
    </div>
</div>

resources/views/livewire/add-favorite-item.blade.php
<div>
    <x-jet-secondary-button class="ml-12" wire:loading.attr="disabled" wire:target="" wire:click="">
        <i class="fas fa-heart text-red-500 text-lg"></i>
    </x-jet-secondary-button>
</div>

resources/views/livewire/cart-mobil.blade.php
<div>
    <a href="{{ route('shopping-cart') }}"
        class="py-2 px-4 text-sm flex items-center text-trueGray-500 hover:bg-Orange-500 hover:text-white">
        <span class="flex justify-center w-9">
            {{-- <i class="fas fa-shopping-cart"></i> --}}
            <x-cart color="#ccc" size="20" />
        </span>
        <span class="relative inline-block pr-4">
            Carrito de compras
            @if (Cart::count())
                <span
                    class="absolute top-0 right-0 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-red-100 transform translate-x-1/2 -translate-y-1/2 bg-red-600 rounded-full">{{ Cart::count() }}</span>
            @else
                <span
                    class="absolute top-0 right-0 inline-block w-2 h-2 transform translate-x-1/2 -translate-y-1/2 bg-red-600 rounded-full"></span>
            @endif
        </span>
    </a>
</div>

resources/views/livewire/category-filter.blade.php
<div>
    <div class="bg-white rounded-lg shadow-lg mb-6">
        <div class="px-6 py-2 flex justify-between items-center">
            <h1 class="font-semibold text-gray-700 uppercase">{{ $category->name }}</h1>
            <div class="hidden md:block grid grid-cols-2 border border-gray-200 divide-x divide-gray-200 ">
                <i class="fas fa-border-all p-3 text-gray-500 cursor-pointer {{ $view == 'grid' ? 'text-Orange-500' : '' }}"
                    wire:click="$set('view', 'grid')"></i>
                <i class="fas fa-th-list p-3 text-gray-500 cursor-pointer {{ $view == 'list' ? 'text-Orange-500' : '' }}"
                    wire:click="$set('view', 'list')"></i>
            </div>
        </div>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-6">
        <aside>
            <h2 class="font-semibold text-center mb-2">Subcategorías</h2>
            <ul class="divide-y divide-gray-200">
                @foreach ($category->subcategories as $subcategory)
                    <li class="py-2 text-sm">
                        <a class="cursor-pointer hover:text-Orange-500 capitalize {{ $subcategoria == $subcategory->slug ? 'text-Orange-500 font-bold' : '' }}"
                            wire:click="$set('subcategoria', '{{ $subcategory->slug }}')">{{ $subcategory->name }}</a>
                    </li>
                @endforeach
            </ul>
            <h2 class="font-semibold text-center mt-4 mb-2">Marcas</h2>
            <ul class="divide-y divide-gray-200">
                @foreach ($category->brands as $brand)
                    <li class="my-2 text-sm">
                        <a class="cursor-pointer hover:text-Orange-500 capitalize {{ $marca == $brand->name ? 'text-Orange-500 font-bold' : '' }}"
                            wire:click="$set('marca','{{ $brand->name }}')">
                            {{ $brand->name }}</a>
                    </li>
                @endforeach
            </ul>
            <x-jet-button class="mt-4" wire:click="limpiar">
                Eliminar filtros
            </x-jet-button>
        </aside>
        <div class="md:col-span-2 lg:col-span-4">
            @if ($view == 'grid')
                <ul class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                    @forelse ($products as $product)
                        <li class="bg-white rounded-lg shadow">
                            <article>
                                <figure>
                                    <img class="h-48 w-full object-cover object-center"
                                        src="{{ Storage::url($product->images->first()->url) }}" alt="products">
                                </figure>
                                <div class="py-4 px-6">
                                    <h1 class="text-lg font-semibold">
                                        <a href="{{ route('products.show', $product) }}">
                                            {{ Str::limit($product->name, 20) }}
                                        </a>
                                    </h1>
                                    <p class="font-bold text-trueGray-700">$MXN {{ $product->price }}</p>
                                </div>
                            </article>
                        </li>
                    @empty
                        <li class="md:col-span-2 lg:col-span-4">
                            <div class="bg-blue-100 border-t border-b border-blue-500 text-blue-700 px-4 py-3"
                                role="alert">
                                <p class="font-bold">Upss!</p>
                                <p class="text-sm">Por el momento no tenemos productos con esos filtros</p>
                            </div>

                        </li>
                    @endforelse
                </ul>
            @else
                <ul>
                    @forelse ($products as $product)
                        <x-product-list :product="$product" />
                    @empty
                        <div class="bg-blue-100 border-t border-b border-blue-500 text-blue-700 px-4 py-3" role="alert">
                            <p class="font-bold">Upss!</p>
                            <p class="text-sm">Por el momento no tenemos productos con esos filtros</p>
                        </div>
                    @endforelse
                </ul>
            @endif
            <div class="mt-4">
                {{ $products->links() }}
            </div>
        </div>
    </div>
</div>

resources/views/livewire/category-products.blade.php
<div wire:init="loadPosts">
    @if (count($products))
        <div class="glider-contain">
            <ul class="glider-{{ $category->id }}">

                @foreach ($products as $product)
                    <li class="bg-white rounded-lg shadow {{ $loop->last ? '' : 'sm:mr-4' }}">
                        <article>
                            <a href="{{ route('products.show', $product) }}">
                                <figure>

                                    @if ($product->images->count())
                                        <img class="h-48 w-full object-cover object-center"
                                            src="{{ Storage::url($product->images->first()->url) }}"
                                            alt="img-{{ $product->slug }}">
                                    @else
                                        <x-icon-product-deafult />
                                    @endif
                                </figure>
                            </a>
                            <div class="py-4 px-6">
                                <h1 class="text-lg font-semibold">
                                    <a href="{{ route('products.show', $product) }}">
                                        {{ Str::limit($product->name, 20) }}
                                    </a>
                                </h1>
                                <p class="font-bold text-trueGray-700">$MXN {{ $product->price }}</p>
                            </div>
                        </article>

                    </li>
                @endforeach
            </ul>

            <button aria-label="Previous" class="glider-prev">«</button>
            <button aria-label="Next" class="glider-next">»</button>
            <div role="tablist" class="dots"></div>
        </div>
    @else
        <div class="mb-4 h-48 flex justify-center items-center bg-white shadow-xl border border-gray-100 rounded-lg">
            <i class="fas fa-spinner animate-spin text-Orange-700 sm:text-5xl text-3xl"></i>
        </div>
    @endif
</div>

resources/views/livewire/update-cart-item-color.blade.php
<div class="flex items-center" x-data>
    <x-jet-secondary-button disabled x-bind:disabled="$wire.qty <= 1" wire:loading.attr="disabled"
        wire:target="decrement" wire:click="decrement">
        -
    </x-jet-secondary-button>
    <span class="mx-2 text-gray-700">{{ $qty }}</span>
    <x-jet-secondary-button x-bind:disabled="$wire.qty >= $wire.quantity" wire:loading.attr="disabled"
        wire:target="increment" wire:click="increment">
        +
    </x-jet-secondary-button>
</div>